---
gitian_user: vagrant
download_directory: /tmp/gitian
vm_builder_name: 'vm-builder-0.12.4+bzr494'
vm_builder_url: 'http://archive.ubuntu.com/ubuntu/pool/universe/v/vm-builder/vm-builder_0.12.4+bzr494.orig.tar.gz'
gitian_builder_url: https://github.com/devrandom/gitian-builder
gitian_builder_version: master
zelcash_git_repo_url: https://github.com/zelcash/zelcash
zelcash_gitian_sigs_repo: https://github.com/zelcash/gitian.sigs
zelcash_version: master
gitian_host_ip: 10.0.2.15
lxc_guest_ip: 10.0.3.5
zelcash_developer_pubkeys:
  - name: milesmanley
    id: AFD3D8B36ABAE6BDED9401991CCB0ADD6BD0A0BE
