---
- name: Apply the Zelcash Gitian builder role.
  become: yes
  hosts: localhost:zelcash-build
  vars:
    zelcash_git_repo_url: "{{ lookup('env','ZELCASH_GIT_REPO_URL') }}"
    zelcash_version: "{{ lookup('env','ZELCASH_VERSION') }}"
    git_name: "{{ lookup('env','GIT_NAME') }}"
    git_email: "{{ lookup('env','GIT_EMAIL') }}"
    gpg_key_name: "{{ lookup('env','GPG_KEY_NAME') }}"
    gpg_key_id: "{{ lookup('env','GPG_KEY_ID') }}"
  roles:
    - role: common
      tags: common
    - role: gitian
      tags: gitian
